baseURL = "http://www.raidadvice.com"
languageCode = "en-us"
title = "RaidAdvice.com"
theme = "slick"
publishDir = "docs"

[permalinks]
  posts = ":title"

[menu]

    # Configure main menu entries (header)
    # Currently set to list all taxonomies and posts
    [[menu.main]]
        identifier = "About"
        name = "About"
        url = "/about/"
        weight = 1

    [[menu.main]]
        identifier = "General-Guides"
        name = "General Raiding Guides"
        url = "/general-raiding-guides/"
        weight = 1
